baseURL = "https://jeffrey-cochran.github.io/"
languageCode = "en-us"
title = ""
theme = "aether"
googleAnalytics = "UA-132562977-1"

[params]
brand = "dontbe.limited"
description = "The website's description"
bgimg = "img/home.jpg"
homeimg = "img/tesselation.jpg"
